name: ekyc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter 
  crypto: ^3.0.6
  intl: ^0.20.2
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
