package com.gtel.ekyc.common

object IntentData {
    val KEY_BUSINESS_TYPE = "KEY_BUSINESS_TYPE"
    val KEY_MRZ_INFO = "KEY_MRZ_INFO"
    val KEY_PASSPORT = "KEY_PASSPORT"
    val KEY_VERIFY_ID_SUCCESS = "KEY_VERIFY_ID_SUCCESS"
    val KEY_FACE_MATCHING_SUCCESS = "KEY_FACE_MATCHING_SUCCESS"
    val KEY_FACE_LIVE = "KEY_FACE_LIVE"
    val KEY_VEHICLE_PLATE_INFO = "KEY_VEHICLE_PLATE_INFO"
    val KEY_QRCODE_INFO = "KEY_QRCODE_INFO"
}
